### ISSUE TITLE
Navigation Menu

### ISSUE THREAD

**Issue by clickclackclark** [clickclackclark/usu-gdsf#10]

**Comment by clickclackclark** [comment]
@WinniCdM are you planning to follow a similar basic layout to what is currently in the left navigation menu? Just curious, I was thinking it might be nice to have an app bar kind of like [this one](https://next.vuetifyjs.com/en/components/app-bars/), that way we have a good place for hiding and showing the nav menu. We could also put the search in the app bar and with something that might bring up the account page. 

Another option if you aren't too far along would be to do something similar to GitHub where there is just the app bar since there aren't too many pages that will need navigation links. 

Anyway if you are already past that point don't worry about it too much, just some thoughts I had. I can also create a new issue for the app bar that we can get assigned after your stuff is merged if you want. Thoughts?

**Comment by WinniCdM** [comment]
@clickclackclark ive taken what he gave us and I adjusted/enhanced it. It does hide away similarly to this one you referenced, and it'll have similar icons for navigating. I'm pretty far along though, so reworking may be troublesome. I can look at it though when I work on this tonight/tomorrow

**Comment by clickclackclark** [comment]
Ok perfect, no worries! No rush and I'm sure it will be great, we can always modify things later if we want and have extra time once there is a good MVP in place.

**Comment by WinniCdM** [comment]
@clickclackclark as a note, Clark, I did try and center the icons but the vuetify package did not have much documentation on how to do that cleanly. Their examples showed them off centered as well. As you said, we can try down the road and center them if we want.
